### ISSUE TITLE
Option for a more minimal theme

### ISSUE THREAD

**Issue by marcii** [tom-james-watson/reddit-comment-collapser#11]
The colours can be a bit distracting, and if there's an options page from #8, another option for something like this would be a nice-to-have:
![collapser](https://cloud.githubusercontent.com/assets/6956633/23667515/08ed8592-0356-11e7-8952-4edd8d4ea0b0.png)

Or, possibly just changing the class names from colours to depth to make it more amenable to user-theming.

**Comment by tom-james-watson** [comment]
Agreed we should support some other kind of collapser style. Have had that requested before. Problem with the image is some subreddits have something very similar in their themes. I'll try and keep an eye out and have a think about other ways of doing it.

**Comment by tom-james-watson** [comment]
Maybe something like the above is fine as long as it changes colour/opacity on hover or something like that

**Comment by marcii** [comment]
Yeah, that's a custom style I use and I had it do an opacity change on hover. I've noticed issues on *some* subreddits where they draw a border or change the indent and it lines up a little too closely, but it's mostly fine. If we keep the current one as default anyway, it shouldn't matter too much.

**Comment by tom-james-watson** [comment]
Ideally it could work just by highlighting the comment itself as opposed to rendering the collapser. For example:

![image](https://cloud.githubusercontent.com/assets/3852719/23668207/ae75df0a-0360-11e7-95f7-793571e56ca4.png)

I think I tried this at first and think maybe it didn't work with a lot of subreddit styles, but could be worth looking into again.

**Comment by marcii** [comment]
How would that work, exactly? Would the click area be in the same place, just without a collapser?

We could probably get the styling to work reliably on most subreddits but if it goes wrong, it *really* goes wrong. Styling on subs with a dark theme (non-RES) could look pretty bad, too.

**Comment by tom-james-watson** [comment]
Yeah, click area in same place. I'll try and find the time to play around with this

**Comment by tom-james-watson** [comment]
The subreddit-style implemented collapsers mentioned in https://github.com/tom-james-watson/reddit-comment-collapser/issues/15 are actually quite nice. Maybe we can look at what they're doing and override/improve (half-off-screen comments that are collapsed leave you in weird place, for example).

**Comment by marcii** [comment]
I've noticed those collapsers on a lot of subs lately, they always annoy me because of the scroll issue and they get in the way of the extension's collapsers.

I've only seen one design, so I assume they're all more or less the same thing. We could ditch all the custom stuff and just hook the scrolling up to the expandos and do everything with stylesheets, overriding those ones. That'd probably a lot more efficient. A lot simpler, too.

**Comment by marcii** [comment]
Something like this?
https://github.com/marcii/reddit-comment-collapser/tree/sans-custom

**Comment by tom-james-watson** [comment]
Yeah! Looks great on https://www.reddit.com/r/wholesomememes/comments/6mekii/our_fishy_friends_deserve_it/

I think it's a good route to go down.

Hopefully it's not too difficult to get it working across all subreddits. Right now it seems to not work on most. So yeah, if we can make it consistently display correctly and fix the scroll-to then it'll be great.

**Comment by marcii** [comment]
Good results with: https://github.com/marcii/reddit-comment-collapser/tree/partial-rewrite

Main problem I see are the subs that use dark themes outside of RES night mode.

**Comment by tom-james-watson** [comment]
It looks good. We can perfect the colours and stuff later. Did you try to get scroll-to working yet?

**Comment by marcii** [comment]
Oh, didn't notice that since I had the experimental features enabled. Was just the missing settings object. Fixed.

**Comment by tom-james-watson** [comment]
Yesss this is awesome. I will try out for a while. We can sort out the exact look later.

**Comment by tom-james-watson** [comment]
Made redundant by https://github.com/tom-james-watson/reddit-comment-collapser/pull/16
