### ISSUE TITLE
Recent update removes color coding making it harder to discern levels quickly

### ISSUE THREAD

**Issue by Caspy7** [tom-james-watson/reddit-comment-collapser#18]
The titles pretty well says it.
Please at least make this an option. The color coding let's me more easily glance and see what level of reply I'm at.

**Comment by tom-james-watson** [comment]
This was added as an option in 5.1.0. 

Click 'Options' on chrome://extensions/

**Comment by Caspy7** [comment]
I'm on Firefox, there is no Options button with the extension in the addons manager.
The current version available on the addons site is 5.0.0 (which is what I have).

**Comment by tom-james-watson** [comment]
We'll be releasing soon, you can track at https://github.com/tom-james-watson/reddit-comment-collapser/issues/8#issuecomment-284730732

**Comment by tom-james-watson** [comment]
5.1.1 has been submitted to addon store for review. Adds preferences to switch back to old theme.
