### ISSUE TITLE
Request: Can the lines not be clickable?

### ISSUE THREAD

**Issue by ImSpecial** [tom-james-watson/reddit-comment-collapser#21]
Love this add-on, the colored lines help me follow long chains much better then without, but I don't like how they are clickable, and I miss click them constantly. I know some or most do like it this way, so maybe have an option to just make the lines there as eye guides but not be clickables that collapse the chains... 

Anyway just a small request I had, nothing more.

**Comment by tom-james-watson** [comment]
Yeah this is definitely doable. I can add an option to disable the collapsing functionality.

**Comment by tom-james-watson** [comment]
I started looking into this and it's not as easy as I hoped. The collapsers are actually part of the link that collapses the comment natively on Reddit. We'd need to completely change how the collapsers are constructed.

**Comment by ImSpecial** [comment]
Ouch that's not good : / 

Thanks for looking into it anyway, I'll cross my fingers that you find and easy solution to this, but also don't stress yourself over it either.

**Comment by tom-james-watson** [comment]
Closing this due to age and because collapsing the comments is kinda the whole point of the extension.
