### ISSUE TITLE
Preferences keep getting lost. Keeps defaulting to Minimalist colors instead of Retro.

### ISSUE THREAD

**Issue by Glazed** [tom-james-watson/reddit-comment-collapser#25]
I've set it back to Retro three times now, and the setting keeps reverting to Minimalist. Seems to happen every time I quit Firefox, but I should test that to make sure. I have many other addons that aren't forgetting their settings. I don't know why this one is.

Firefox 79.0 for Windows.

**Comment by Glazed** [comment]
Closing Firefox wasn't enough to cause it to lose my preference. It was only after I ran CCleaner. I reproduced it clearing the preference several times. I've been using both CCleaner and this addon for a very long time, but this issue is a new development. I narrowed it down to the "Internet Cache" cleaning option. 

It doesn't make much sense to me why this addon would store a preference in anything to do with the cache, so I tested is several more times. If I ran CCleaner with every Firefox cleaning option on _except_ "Internet Cache" (or Cookies or Saved Passwords, which I never clear using CCleaner), I wouldn't lose the preference. If I ran it with "Internet Cache" enabled by itself or with all the other settings on, then it would clear my color preference.

There were only three files being clears each time. They were all zero bytes and had funny names. I didn't browse the web in between tests at all. I simply opened the addons screen, clicked this addon, and looked at the options. If needed, I would set it back to Retro and hit save. I would even close and reopen Firefox to verify that it was being saved between sessions. Then I would run CCleaner again and it would revert to Minimalist.

And then this behavior suddenly went away! I can no longer reproduce the clearing of the option no matter what I try! I'm so confused.

**Comment by tom-james-watson** [comment]
This extension is extremely basic. I've just double checked the docs and its usage and it is using the chrome.storage.sync as it should. https://developer.chrome.com/extensions/storage

If CCleaner is doing something to wipe these settings then that's a bug with CCleaner, I'm afraid!
