### ISSUE TITLE
Colored dotted lines for comment collapse are not visible in current version

### ISSUE THREAD

**Issue by navinthomas** [tom-james-watson/reddit-comment-collapser#26]
### Screenshot
![image](https://user-images.githubusercontent.com/34918736/169232003-23725aa4-67d9-427c-a080-622dde5577e0.png)

### System Details

Browser: Firefox & Chrome
Reddit: Old Reddit
RES Installed?: Yes

**Comment by tom-james-watson** [comment]
Change collapser style to "retro":

![image](https://user-images.githubusercontent.com/3852719/169239303-fe325363-3162-4832-a6f9-0adc7b94a7de.png)

**Comment by navinthomas** [comment]
Ah. I missed that completely. Any particular reason why Minimal is set as the default? All the screenshots in Firefox and Chrome web stores show the Retro look. I installed the extension to get the colored collapse lines, and I wrongly assumed it was not working when I saw the minimal look. I didn't know I had to change it in preferences.

**Comment by navinthomas** [comment]
OK. Got it. I have two questions. I hope it's okay to ask here, since I can't figure out a better place

- What is the  purpose of the Scroll Animation checkbox? I tried turning it off and on and did not notice any difference.
- Would it be possible to add a new style that is similar to Minimalist, but with the same colouring style of Retro? Basically, thick collapse bars/lines like that of Minimalist style, but with color coding like that of Retro style to indicate the comment's hierarchy.
