### ISSUE TITLE
Problem with threadlines on comments

### ISSUE THREAD

**Issue by GrosBourrin** [tom-james-watson/reddit-comment-collapser#29]
![GvwLWAUi6R](https://github.com/tom-james-watson/reddit-comment-collapser/assets/40931468/749bc8b0-b0e0-4459-a7ba-2ec11474a77f)

FireFox 113 x64 windows 10
when i deactivate your extension, all is good but when reactivate it it does again this issue,

**Comment by tom-james-watson** [comment]
That doesn't look like standard Reddit styling. Some subreddits have custom styling that might mess with the extension. Does this happen on all subreddits? Can you please link to an example page you see this on?

**Comment by tom-james-watson** [comment]
Honestly this looks like new reddit styling. Can you confirm you are on old.reddit.com?
