### ISSUE TITLE
Enable support for Firefox on Android 

### ISSUE THREAD

**Issue by matrixik** [tom-james-watson/reddit-comment-collapser#30]
Would be great if you could make it visible as Firefox on Android addon as it's working fine.

Just maybe it has too much of left and right margin on the mobile phone.

**Comment by tom-james-watson** [comment]
Hello. It is already enabled. Just navigate to https://addons.mozilla.org/en-GB/firefox/addon/old-reddit-redirect/ and press add.

**Comment by matrixik** [comment]
Yes, it's working but it's not showing up when you search for it on Android https://addons.mozilla.org/pl/android/search/?q=Reddit%20collapser

**Comment by tom-james-watson** [comment]
Sorry I thought this was a comment on my other extension.

**Comment by matrixik** [comment]
Then I can confirm that Reddit comments collapser is working fine on Firefox on Android. As I mentioned in the first comment maybe it has too much left and right margin.
I was able to install it by going to it's Firefox add-on page and reloading it as desktop site.
