### ISSUE TITLE
Stopped working with 6.0.0 update

### ISSUE THREAD

**Issue by Stone-D** [tom-james-watson/reddit-comment-collapser#31]
Yesterday Chrome (Windows 10, RES v5.24.4) updated this extension to v6 and no longer works. Nothing clickable, no lines.

**Comment by tom-james-watson** [comment]
Can you try disabling all your other extensions and checking if it still works?

**Comment by Stone-D** [comment]
If I disable RES, it works but with nothing visible - no colors, just something 'there' to click.

I managed to download 5.1.2 which works as expected.

**Comment by tom-james-watson** [comment]
Rolling back is not really an option because this is a forced migration to manifest V3, without which the extension will be removed from the chrome web store.

It works fine for me, curious to hear from anybody else.

Can you try disabling all other extensions?

**Comment by Zachswan1** [comment]
I think I've discovered the issue: it only works on old.reddit.com, even if you have your Reddit settings set to show the old layout by default. And for some reason, you can't change the extension's settings to allow it to read and change site data on any other sites, like you able to do with some other Chrome extensions. Here are a few screenshots to demonstrate the problem:

<img width="614" alt="Reddit" src="https://github.com/tom-james-watson/reddit-comment-collapser/assets/4589319/efe33e31-9f82-480e-bce9-b01d66a68ce1">

<img width="786" alt="Old Reddit" src="https://github.com/tom-james-watson/reddit-comment-collapser/assets/4589319/441b7976-14d8-47fa-9090-6f4049e323fd">

<img width="536" alt="On All Sites" src="https://github.com/tom-james-watson/reddit-comment-collapser/assets/4589319/1ed80fd5-a2b9-41f5-b726-07a2ea63ea5b">

<img width="672" alt="Site Access" src="https://github.com/tom-james-watson/reddit-comment-collapser/assets/4589319/44e28bae-eaf8-4ca2-b465-b6f1c1e753b4">

**Comment by magkri** [comment]
It works if used with [Old Reddit Redirect](https://github.com/tom-james-watson/old-reddit-redirect).

**Comment by tom-james-watson** [comment]
Ahhhh ok, thank you for the explanation. This should be an easy fix. Yes, as I use old reddit redirect I never noticed this.

**Comment by tom-james-watson** [comment]
I've just created a new v6.0.1 which should fix this. Might take a few hours (sometimes days) for the new version to be approved.

**Comment by Stone-D** [comment]
It works! Cheers for the rapid fix, Tom.
