### ISSUE TITLE
Get storage working on firefox

### ISSUE THREAD

**Issue by tom-james-watson** [tom-james-watson/reddit-comment-collapser#8]
Haven't looked into it properly but it looks like might need to add a chrome version and a firefox version :(

https://developer.chrome.com/extensions/options

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Implement_a_settings_page

**Comment by marcii** [comment]
Options V2, that's what the moz docs are using. Should be fine with one for both browsers.
https://developer.chrome.com/extensions/optionsV2

Firefox doesn't support the `"chrome_style"` key yet, which would give us a nice integrated style, though.

**Comment by tom-james-watson** [comment]
Done. Also added an option to switch back to the "retro" theme, as per requests in extension reviews. Unfortunately `chrome.storage` does not seem to be working properly on Frefox so I'll only update Chrome for now.

**Comment by marcii** [comment]
> Note that the implementation of sync.storage in Firefox relies on the Add-on ID. If you use sync.storage, you must set an ID for your extension using the applications manifest.json key.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/sync

**Comment by tom-james-watson** [comment]
Done. Thanks @marcii. 5.1.1 has been submitted to firefox addon store for review.
